### ISSUE TITLE
Doesn't work with IC2 classic 

### ISSUE THREAD

**Issue by parcel31u** [ternsip/StabilizerMod#1]

**Comment by ternsip** [comment]
Can you give me crash report with description please. "Doesn't work" does not make any sense for me

**Comment by ternsip** [comment]
Ahhh din't know about IC2 Classic, cause every time I used IC2 Experimental. Now I try to figure out problem source.

**Comment by ternsip** [comment]
Now version 2.3 works with ic2 classic. Thanks for your issue.
