### ISSUE TITLE
duplicate mod examplemod

### ISSUE THREAD

**Issue by SvEgiiVEteR** [ternsip/StabilizerMod#2]
Found a duplicate mod examplemod at [D:\sobirau\.minecraft\mods\weaponmod-1.14.3-hotfixSV.jar, D:\sobirau\.minecraft\mods\Stabilizer-2.3-1.7.10.jar]
http://i.imgur.com/O1U0MYV.png

**Comment by ternsip** [comment]
Fixed. Just Redownload mod.
